---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pushprom
  namespace: <NAMESPACE>
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pushprom
    spec:
      containers:
      - name: pushprom
        image: messagebird/pushprom
        ports:
        - containerPort: 9090
          protocol: UDP
        - containerPort: 9091
          protocol: TCP